---
- name: Install firmware packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: 'present'
  loop:
    - 'firmware-linux'
    - 'firmware-linux-free'
    - 'firmware-linux-nonfree'
    - 'firmware-misc-nonfree'
    - 'fwupd'
    - 'fwupd-amd64-signed'
    - 'fwupd-doc'
    - 'fwupd-unsigned'
    - 'gnome-firmware'
