---
- name: run optional versioncheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: download additional firmware on apu board
  ansible.builtin.include_tasks: kernel_firmware_download.yml
  when:
    - ansible_board_name == 'APU'
    - ansible_product_name == 'APU'
