---
- name: Run optional versioncheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'
  when:
    - submodules_versioncheck | bool

- name: Install some firmware packages
  ansible.builtin.include_tasks:
    file: 'firmware.yml'

- name: Download additional firmware on apu board
  ansible.builtin.include_tasks:
    file: 'kernel_firmware_download.yml'
  when:
    - ansible_processor[1] == 'AuthenticAMD'
